# Generated by Django 3.0.8 on 2020-07-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='language_slug',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='technology_slug',
            new_name='technology',
        ),
    ]
