# Generated by Django 3.0.8 on 2020-07-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
