# Generated by Django 3.0.8 on 2020-07-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20200715_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='total_packages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='technology',
            name='total_packages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
