# Generated by Django 3.0.8 on 2020-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_package_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
