# Generated by Django 3.0.8 on 2020-09-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20200805_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('slug', models.SlugField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('total_packages', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.Skill'),
        ),
    ]
