# Generated by Django 3.0.8 on 2020-11-26 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_auto_20200901_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.Language'),
        ),
        migrations.AlterField(
            model_name='package',
            name='technology',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.Technology'),
        ),
    ]
