# Generated by Django 3.0.8 on 2021-02-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_auto_20210203_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='skills',
            field=models.ManyToManyField(to='package.Skill'),
        ),
    ]
